# Setup
title:        nlpfm
tagline:      自然语言处理
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       nlpfm
  url:        https://nlpfm.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
